# Generated by Django 3.0.6 on 2021-07-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('founder', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=250)),
                ('date', models.DateField()),
                ('averageRating', models.FloatField()),
            ],
        ),
    ]
