# Generated by Django 3.0.6 on 2021-07-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.URLField(default=None, null=True),
        ),
    ]
